builds:
  - binary: felix
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.Version={{.Version}} -X main.GitSummary={{.Commit}} -X main.BuildDate={{.Date}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - VERSION
    - config.example.yml
