builds:
  - binary: felix
    goos:
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.Version={{.Version}} -X main.GitSummary={{.Commit}} -X main.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - VERSION
    - config.example.yml
