language: go

install: go get -v -t -u ./...

script: ./coverage.sh

after_success:
  - [ "$TRAVIS_TAG" = "" ] && bash <(curl -s https://codecov.io/bash) || echo 'Tag build detected. Not uploading coverage (codecov).'
